UI: Inputs
mirea-ninja/rtu-app-core pull request #1
Opened 2022-08-17 12:30 UTC by L3odr0id

Реализованы 3 типа ввода и билдер-шаблон для выбора один-из-многих

![telegram-cloud-photo-size-2-5469966101195635724-y](https://user-images.githubusercontent.com/62698748/185120619-32c73296-e001-4b08-be4d-799dd80ff272.jpg)

2022-08-17 12:31 UTC, Dragonprod commented
Insane

2022-08-17 13:24 UTC, 0niel requested changes

2022-08-17 13:24 UTC, 0niel commented on example/lib/main.dart
> +              child: NinjaInputFilled(
Виджет поиска вышел слишком большим. Он должен растягиваться по ширине, но быть не выше 44 в высоту. Сейчас у него высота = 59.
![image](https://user-images.githubusercontent.com/51058739/185142903-401c0105-d678-4872-8c7f-3958cd5659ee.png)

2022-08-17 13:24 UTC, 0niel commented on lib/src/widgets/input/ninja_input_basic.dart
> +          hintStyle: NinjaTextStyle.bodyMedium(color: hintColor),
У этих инпутов используется `NinjaTextStyle.bodyLarge` с разными fontWeight. Может стоит предусмотреть передачу стиля текста в качестве аргументов?

![image](https://user-images.githubusercontent.com/51058739/185141971-05016c9e-d1e6-4f2c-bd9a-a8263e60c183.png)
![image](https://user-images.githubusercontent.com/51058739/185145072-775501ea-2ce7-4e07-b841-945bafe4e045.png)

2022-08-17 13:24 UTC, 0niel commented on lib/src/widgets/input/ninja_input_filled.dart
> +      border: NinjaInputThemes.fullBorder(context).border,
У данного типа инпута не должно быть границ. 
![image](https://user-images.githubusercontent.com/51058739/185140761-da459bf7-19bb-463d-87f1-0296b4fa1137.png)

2022-08-17 13:24 UTC, 0niel commented on lib/src/widgets/input/ninja_input_filled.dart
> +      fillColor: NinjaConstant.grey200,
По умолчанию должен быть цвет `#F9F9F9`, что соответствует `NinjaConstant.grey50`

2022-08-17 13:24 UTC, 0niel commented on example/lib/main.dart
> +                    NinjaText.bodyLarge(
Нужно не забывать, что у этого виджета тут fontWeight должен быть равен 500.

2022-08-17 13:24 UTC, 0niel commented on example/lib/main.dart
> +              child: NinjaInputUnderlined(
У этого типа инпута должен быть отступ 16 от нижней линии. Этого можно добиться, если добавить в `InputDecoration` следующее:
```
contentPadding: const EdgeInsets.symmetric(vertical: 16),
isDense: true,
```

2022-08-17 13:29 UTC, L3odr0id commented
@0niel , спасибо.

Насчёт fontweight и шрифтов. Я умышленно оставил их со стоковыми настройками, чтобы не плодить 1000 вариантов. Мне не особо нравится, что у нас получается куча одноразовых настроек вместо стандартизации шрифтов. Однако, доделать это не проблема

2022-08-18 06:10 UTC, L3odr0id commented on lib/src/widgets/input/ninja_input_filled.dart
> +      border: NinjaInputThemes.fullBorder(context).border,
В том числе не должно быть подсветки границ при фокусе?

2022-08-18 07:05 UTC, L3odr0id commented
Пофиксил высоту, fontweight, некоторые цвета и отступы. Плюс реализовал example для ввода пароля с `suffixIcon`

2022-08-18 10:05 UTC, 0niel requested changes
@L3odr0id, всё круто! Осталось только добавить circular border radius для `NinjaInputFilled`

2022-08-18 10:05 UTC, 0niel commented on lib/src/widgets/input/ninja_input_filled.dart
> +      border: InputBorder.none,
Нужен borderRadius 10 (circular), как в фигме, но без видимых границ.
![image](https://user-images.githubusercontent.com/51058739/185369205-1175a574-af9d-43f5-81c3-e182fdab9b35.png)

2022-08-18 10:31 UTC, L3odr0id commented on lib/src/widgets/input/ninja_input_filled.dart
> +      border: InputBorder.none,
Справедливо. Пофиксил

2022-08-18 10:41 UTC, 0niel approved these changes

2022-08-18 10:41 UTC, merged

2022-08-18 10:42 UTC, 0niel commented
LGTM! Спасибо!